# frozen_string_literal: true

source 'https://rubygems.org' do
  ruby '2.4.1'
  gem 'berkshelf'
  gem 'bundler'
  gem 'foodcritic'
  gem 'inspec'
  gem 'kitchen-inspec'
  gem 'kitchen-vagrant'
  gem 'net-ssh-gateway'
  gem 'rake'
  gem 'rspec_junit_formatter'
  gem 'rubocop'
  gem 'rubocop-checkstyle_formatter'
  gem 'serverspec'
  gem 'stove'
  gem 'test-kitchen'
end
